arb-dir: lib/l10n
template-arb-file: app_bs.arb
output-localizations-file: app_localizations.dart
output-class: AppLocalizations
nullable-getter: false
untranslated-messages-file: lib/l10n/untranslated.json
