import 'dart:io';
import 'dart:typed_data';

import 'package:archive/archive.dart';
import 'package:csv/csv.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

import '../../../domain/entities/progress/analytics_report.dart';
import '../../../domain/entities/progress/analytics_summary.dart';

/// Supported report export formats.
enum ReportFormat { csv, pdf, excel }

/// Exports an [AnalyticsReport] to CSV, PDF or Excel and shares it.
///
/// Files are written to the app documents directory so they can be opened,
/// shared or backed up. Report labels are kept in English to guarantee the
/// generated documents render correctly everywhere.
class ReportExporter {
  ReportExporter();

  /// Writes the report in [format] and returns the absolute file path.
  Future<String> export(
    AnalyticsReport report,
    ReportFormat format,
  ) async {
    return switch (format) {
      ReportFormat.csv => exportCsv(report),
      ReportFormat.pdf => exportPdf(report),
      ReportFormat.excel => exportExcel(report),
    };
  }

  /// Writes a CSV file and returns its path.
  Future<String> exportCsv(AnalyticsReport report) async {
    final List<List<Object?>> rows = _buildRows(report);
    final String csv = const CsvEncoder().convert(rows);
    final File file = await _file('nexfit_report_${_stamp()}.csv');
    await file.writeAsString(csv);
    return file.path;
  }

  /// Writes a PDF file and returns its path.
  Future<String> exportPdf(AnalyticsReport report) async {
    final pw.Document document = pw.Document(
      title: 'NexFit Report',
      author: 'NexFit',
    );
    final List<List<Object?>> rows = _buildRows(report);

    document.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) => <pw.Widget>[
          pw.Text(
            'NexFit - Progress Report',
            style: pw.TextStyle(
              fontSize: 20,
              fontWeight: pw.FontWeight.bold,
              color: PdfColor.fromInt(0xFF0E9F6E),
            ),
          ),
          pw.SizedBox(height: 6),
          pw.Text(
            _periodLabel(report),
            style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700),
          ),
          pw.SizedBox(height: 16),
          pw.TableHelper.fromTextArray(
            headers: _rowHeaders(rows),
            data: _dataRows(rows),
            headerStyle: pw.TextStyle(
              color: PdfColors.white,
              fontWeight: pw.FontWeight.bold,
            ),
            headerDecoration: const pw.BoxDecoration(
              color: PdfColor.fromInt(0xFF0E9F6E),
            ),
            cellStyle: const pw.TextStyle(fontSize: 10),
            cellPadding: const pw.EdgeInsets.all(6),
          ),
          pw.SizedBox(height: 12),
          pw.Text(
            'Generated by NexFit',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey),
          ),
        ],
      ),
    );

    final Uint8List bytes = await document.save();
    final File file = await _file('nexfit_report_${_stamp()}.pdf');
    await file.writeAsBytes(bytes);
    return file.path;
  }

  /// Writes an Excel (.xlsx) file and returns its path.
  Future<String> exportExcel(AnalyticsReport report) async {
    final List<List<Object?>> rows = _buildRows(report);
    final Uint8List bytes = _buildXlsx(rows);
    final File file = await _file('nexfit_report_${_stamp()}.xlsx');
    await file.writeAsBytes(bytes);
    return file.path;
  }

  /// Shares a file previously written to disk.
  Future<void> share(String path) async {
    await SharePlus.instance.share(
      ShareParams(
        files: <XFile>[XFile(path)],
        subject: 'NexFit Report',
        text: 'My fitness progress report from NexFit.',
      ),
    );
  }

  /// Builds the tabular data backing every export format.
  List<List<Object?>> _buildRows(AnalyticsReport report) {
    final AnalyticsSummary s = report.summary;
    return <List<Object?>>[
      <Object?>['Metric', 'Value'],
      <Object?>['Period', _periodLabel(report)],
      <Object?>['Workouts', s.workoutCount],
      <Object?>['Active days', s.activeDays],
      <Object?>['Workout minutes', s.workoutMinutes.toStringAsFixed(0)],
      <Object?>['Calories burned', s.caloriesBurned.toStringAsFixed(0)],
      <Object?>['Calories consumed', s.caloriesConsumed.toStringAsFixed(0)],
      <Object?>['Water (ml)', s.waterMl],
      <Object?>['Steps', s.steps],
      <Object?>['Sleep (hours)', (s.sleepMinutes / 60).toStringAsFixed(1)],
      if (s.weightStartKg != null && s.weightEndKg != null) ...[
        <Object?>['Weight start (kg)', s.weightStartKg!.toStringAsFixed(1)],
        <Object?>['Weight end (kg)', s.weightEndKg!.toStringAsFixed(1)],
        <Object?>['Weight change (kg)', s.weightChangeKg!.toStringAsFixed(1)],
      ],
      if (s.bmiStart != null && s.bmiEnd != null) ...[
        <Object?>['BMI start', s.bmiStart!.toStringAsFixed(1)],
        <Object?>['BMI end', s.bmiEnd!.toStringAsFixed(1)],
      ],
      <Object?>[],
      <Object?>[
        'Date',
        'Calories burned',
        'Calories consumed',
        'Workout min',
        'Workouts',
        'Water (ml)',
        'Steps',
        'Sleep (h)',
        'Weight (kg)',
      ],
      for (final point in report.series)
        <Object?>[
          _dateLabel(point.date),
          point.caloriesBurned.toStringAsFixed(0),
          point.caloriesConsumed.toStringAsFixed(0),
          point.workoutMinutes.toStringAsFixed(0),
          point.workoutCount,
          point.waterMl,
          point.steps,
          (point.sleepMinutes / 60).toStringAsFixed(1),
          point.weightKg?.toStringAsFixed(1) ?? '',
        ],
    ];
  }

  List<String> _rowHeaders(List<List<Object?>> rows) {
    for (final List<Object?> row in rows) {
      if (row.isNotEmpty && row.first == 'Metric') {
        return row.map((Object? cell) => cell.toString()).toList();
      }
    }
    return <String>['Metric', 'Value'];
  }

  List<List<String>> _dataRows(List<List<Object?>> rows) {
    final int headerIndex = rows.indexWhere(
      (List<Object?> row) => row.isNotEmpty && row.first == 'Metric',
    );
    return rows
        .skip(headerIndex + 1)
        .map(
          (List<Object?> row) => row
              .map((Object? cell) => cell?.toString() ?? '')
              .toList(),
        )
        .toList();
  }

  /// Minimal OOXML writer producing a valid .xlsx workbook (ZIP of XML parts).
  Uint8List _buildXlsx(List<List<Object?>> rows) {
    final StringBuffer sheet = StringBuffer()
      ..writeln('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>')
      ..writeln(
        '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">',
      )
      ..writeln('<sheetData>');
    for (int r = 0; r < rows.length; r++) {
      sheet.writeln('<row r="${r + 1}">');
      final List<Object?> row = rows[r];
      for (int c = 0; c < row.length; c++) {
        final Object? value = row[c];
        final String ref = '${_columnLetter(c)}${r + 1}';
        if (value is num) {
          sheet.writeln('<c r="$ref"><v>$value</v></c>');
        } else if (value is bool) {
          sheet.writeln(
            '<c r="$ref" t="b"><v>${value ? 1 : 0}</v></c>',
          );
        } else {
          final String text = _escapeXml(value?.toString() ?? '');
          sheet.writeln(
            '<c r="$ref" t="inlineStr"><is><t xml:space="preserve">$text</t></is></c>',
          );
        }
      }
      sheet.writeln('</row>');
    }
    sheet.writeln('</sheetData></worksheet>');

    final Archive archive = Archive();
    archive.addFile(
      ArchiveFile.string(
        '[Content_Types].xml',
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
        '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
        '<Default Extension="xml" ContentType="application/xml"/>'
        '<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>'
        '<Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>'
        '</Types>',
      ),
    );
    archive.addFile(
      ArchiveFile.string(
        '_rels/.rels',
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>'
        '</Relationships>',
      ),
    );
    archive.addFile(
      ArchiveFile.string(
        'xl/workbook.xml',
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" '
        'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
        '<sheets><sheet name="NexFit Report" sheetId="1" r:id="rId1"/></sheets></workbook>',
      ),
    );
    archive.addFile(
      ArchiveFile.string(
        'xl/_rels/workbook.xml.rels',
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>'
        '</Relationships>',
      ),
    );
    archive.addFile(ArchiveFile.string('xl/worksheets/sheet1.xml', sheet.toString()));

    final Uint8List encoded = Uint8List.fromList(ZipEncoder().encode(archive));
    return encoded;
  }

  String _columnLetter(int index) {
    final StringBuffer buffer = StringBuffer();
    int value = index + 1;
    while (value > 0) {
      final int remainder = (value - 1) % 26;
      buffer.write(String.fromCharCode(65 + remainder));
      value = (value - 1) ~/ 26;
    }
    return buffer.toString();
  }

  String _escapeXml(String value) {
    return value
        .replaceAll('&', '&amp;')
        .replaceAll('<', '&lt;')
        .replaceAll('>', '&gt;')
        .replaceAll('"', '&quot;')
        .replaceAll("'", '&apos;');
  }

  Future<File> _file(String name) async {
    final Directory dir = await getApplicationDocumentsDirectory();
    return File('${dir.path}${Platform.pathSeparator}$name');
  }

  String _periodLabel(AnalyticsReport report) {
    return '${_dateLabel(report.start)} - ${_dateLabel(report.end)}';
  }

  String _dateLabel(DateTime date) {
    final String month = date.month.toString().padLeft(2, '0');
    final String day = date.day.toString().padLeft(2, '0');
    return '${date.year}-$month-$day';
  }

  String _stamp() {
    final DateTime now = DateTime.now();
    final String h = now.hour.toString().padLeft(2, '0');
    final String m = now.minute.toString().padLeft(2, '0');
    final String s = now.second.toString().padLeft(2, '0');
    return '${_dateLabel(now)}_$h$m$s';
  }
}
